CREATE TABLE IF NOT EXISTS VAGAS (
    id SERIAL PRIMARY KEY,
    tipo VARCHAR(10) NOT NULL CHECK (tipo IN ('COMUM', 'IDOSO', 'DEFICIENTE')),
    disponivel BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS CARROS (
    id SERIAL PRIMARY KEY,
    placa VARCHAR(7) NOT NULL UNIQUE,
    modelo VARCHAR(50) NOT NULL,
    cor VARCHAR(20),
    hora_entrada TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    hora_saida TIMESTAMP,
    vaga_id INTEGER REFERENCES VAGAS(id)
);